#!/usr/bin/env ruby

require './todo'
require './todo_view'
require './todo_controller'

# <<-DOCUMENTATION

#   ./todo

#   todo> add "item description"
#   todo> list
#   todo> remove item_id

# DOCUMENTATION

puts 'type exit to leave the program'
loop do
  print 'todo> '
  matches = gets.chomp.match(/^(\w+)\s*(.*)$/)
  next if matches.nil?
  command = matches[1]
  argument = matches[2]
  break if %w(exit quit q).include? command
  Controller.new.run_command(command, argument)
end
